
export const UI_TRANSLATIONS = {
  en: {
    home: 'Home',
    quran: 'Quran',
    audio: 'Audio',
    hadis: 'Hadith',
    settings: 'Settings',
    lastRead: 'Last Read',
    surahs: 'Surahs',
    juz: 'Juz',
    language: 'Language',
    fontSize: 'Font Size',
    theme: 'Theme',
    appearance: 'Appearance',
    searchPlaceholder: 'Search surah or keyword...',
    arabicFont: 'Arabic Font Size',
    transFont: 'Translation Font Size',
    noBookmarks: 'No bookmarks yet',
    readMore: 'Read More',
    revelation: 'Revelation',
    ayahs: 'Ayahs',
    bismillah: 'In the name of Allah, the Entirely Merciful, the Especially Merciful',
    prayerTimes: 'Prayer Times',
    sahri: 'Sahri',
    iftar: 'Iftar',
    ramadanCountdown: 'Ramadan Countdown',
    daysLeft: 'days left',
    fajr: 'Fajr',
    dhuhr: 'Dhuhr',
    asr: 'Asr',
    maghrib: 'Maghrib',
    isha: 'Isha',
    currentLocation: 'Detecting Location...',
    playRecitation: 'Play Recitation',
    hadithCollection: 'Hadith Collection',
    audioQuran: 'Audio Quran',
    reciters: 'Reciters',
    bookmarks: 'Bookmarks',
    search: 'Search',
    tafsir: 'Tafsir',
    offlineContent: 'Offline Content',
    downloads: 'Downloads',
    quranText: 'Quran Text',
    audioFiles: 'Audio Files',
    storageUsed: 'Storage Used',
    manageDownloads: 'Manage Downloads',
    downloading: 'Downloading...',
    downloadComplete: 'Download Complete',
    deleteData: 'Delete Data',
    cacheCleared: 'Cache Cleared',
    downloadAll: 'Download All',
    aboutApp: 'About App',
    developerInfo: 'Developer Info',
    donation: 'Support & Donation',
    developedBy: 'Developed by',
    developerName: 'Md Shahin',
    developerRole: 'Full Stack Developer',
    donateMsg: 'If you like this app, please consider supporting us to keep it ad-free and maintained.',
    donateBtn: 'Donate Now',
    contact: 'Contact',
    email: 'Email',
    donateTitle: 'Donate Now',
    bankAccount: 'Bank Account',
    personal: 'Personal',
    copied: 'Copied!',
    tasbih: 'Tasbih',
    count: 'Count',
    reset: 'Reset',
    target: 'Target',
    vibration: 'Vibration',
    games: 'Islamic Learning Games',
    quizGame: 'Quiz Master',
    timelineGame: 'History Timeline',
    surahGame: 'Surah Builder',
    score: 'Score',
    playAgain: 'Play Again',
    correct: 'Correct!',
    wrong: 'Wrong!',
    nextQuestion: 'Next Question',
    gameOver: 'Game Over',
    finalScore: 'Final Score',
    start: 'Start',
    categories: 'Categories',
    prophets: 'Prophets',
    history: 'History',
    pillars: 'Pillars of Islam',
    arrangeEvents: 'Arrange events in order',
    arrangeAyahs: 'Arrange Ayahs in order',
    checkOrder: 'Check Order',
    tryAgain: 'Try Again',
    correctOrder: 'Correct Order!',
    wrongOrder: 'Incorrect Order',
    completed: 'Completed'
  },
  bn: {
    home: 'হোম',
    quran: 'কুরআন',
    audio: 'অডিও',
    hadis: 'হাদিস',
    settings: 'সেটিংস',
    lastRead: 'সর্বশেষ পঠিত',
    surahs: 'সূরাসমূহ',
    juz: 'পারা',
    language: 'ভাষা',
    fontSize: 'ফন্টের আকার',
    theme: 'থিম',
    appearance: 'চেহারা',
    searchPlaceholder: 'সূরা বা শব্দ খুঁজুন...',
    arabicFont: 'আরবি ফন্ট সাইজ',
    transFont: 'অনুবাদ ফন্ট সাইজ',
    noBookmarks: 'কোন বুকমার্ক নেই',
    readMore: 'আরও পড়ুন',
    revelation: 'অবতীর্ণ',
    ayahs: 'আয়াত',
    bismillah: 'পরম করুণাময় অসীম দয়ালু আল্লাহর নামে শুরু করছি',
    prayerTimes: 'নামাজের সময়',
    sahri: 'সেহরি',
    iftar: 'イফাতার',
    ramadanCountdown: 'রমজান কাউন্টডাউন',
    daysLeft: 'দিন বাকি',
    fajr: 'ফজর',
    dhuhr: 'যোহর',
    asr: 'আসর',
    maghrib: 'মাগরিব',
    isha: 'এশা',
    currentLocation: 'অবস্থান শনাক্ত করা হচ্ছে...',
    playRecitation: 'তেলাওয়াত শুনুন',
    hadithCollection: 'হাদিস সংগ্রহ',
    audioQuran: 'অডিও কুরআন',
    reciters: 'কারীগণ',
    bookmarks: 'বুকমার্ক',
    search: 'খুঁজুন',
    tafsir: 'তাফসীর',
    offlineContent: 'অফলাইন কন্টেন্ট',
    downloads: 'ডাউনলোড',
    quranText: 'কুরআন টেক্সট',
    audioFiles: 'অডিও ফাইল',
    storageUsed: 'ব্যবহৃত স্টোরেজ',
    manageDownloads: 'ডাউনলোড পরিচালনা',
    downloading: 'ডাউনলোড হচ্ছে...',
    downloadComplete: 'ডাউনলোড সম্পন্ন',
    deleteData: 'ডেটা মুছে ফেলুন',
    cacheCleared: 'ক্যাশে পরিষ্কার করা হয়েছে',
    downloadAll: 'সব ডাউনলোড করুন',
    aboutApp: 'অ্যাপ সম্পর্কে',
    developerInfo: 'ডেভেলপার তথ্য',
    donation: 'দান ও সহযোগিতা',
    developedBy: 'ডেভেলপার',
    developerName: 'মোঃ শাহিন',
    developerRole: 'ফুল স্ট্যাক ডেভেলপার',
    donateMsg: 'আপনি যদি এই অ্যাপটি পছন্দ করেন, তবে এটি বিজ্ঞাপনমুক্ত এবং রক্ষণাবেক্ষণ রাখতে আমাদের সহযোগিতা করুন।',
    donateBtn: 'এখনই ডোনেট করুন',
    contact: 'যোগাযোগ',
    email: 'ইমেইল',
    donateTitle: 'এখনই ডোনেট করুন',
    bankAccount: 'ব্যাংক অ্যাকাউন্ট',
    personal: 'পার্সোনাল',
    copied: 'কপি করা হয়েছে!',
    tasbih: 'তাসবিহ',
    count: 'গণনা',
    reset: 'রিসেট',
    target: 'লক্ষ্য',
    vibration: 'ভাইব্রেশন',
    games: 'ইসলামি শিক্ষামূলক গেমস',
    quizGame: 'কুইজ মাস্টার',
    timelineGame: 'ইতিহাসের সময়রেখা',
    surahGame: 'সূরা বিল্ডার',
    score: 'স্কোর',
    playAgain: 'আবার খেলুন',
    correct: 'সঠিক!',
    wrong: 'ভুল!',
    nextQuestion: 'পরবর্তী প্রশ্ন',
    gameOver: 'খেলা শেষ',
    finalScore: 'চূড়ান্ত স্কোর',
    start: 'শুরু',
    categories: 'বিভাগ',
    prophets: 'নবীগণ',
    history: 'ইতিহাস',
    pillars: 'ইসলামের স্তম্ভ',
    arrangeEvents: 'ঘটনাগুলো ক্রমানুসারে সাজান',
    arrangeAyahs: 'আয়াতগুলো ক্রমানুসারে সাজান',
    checkOrder: 'যাচাই করুন',
    tryAgain: 'আবার চেষ্টা করুন',
    correctOrder: 'সঠিক ক্রম!',
    wrongOrder: 'ভুল ক্রম',
    completed: 'সম্পন্ন'
  },
  hi: {
    home: 'होम',
    quran: 'क़ुरान',
    audio: 'ऑडियो',
    hadis: 'हदीस',
    settings: 'सेटिंग्स',
    lastRead: 'पिछली बार पढ़ा',
    surahs: 'सूरा',
    juz: 'पारा',
    language: 'भाषा',
    fontSize: 'फ़ॉन्ट आकार',
    theme: 'थीम',
    appearance: 'दिखावट',
    searchPlaceholder: 'सूरा या शब्द खोजें...',
    arabicFont: 'अरबी फ़ॉन्ट आकार',
    transFont: 'अनुवाद फ़ॉन्ट आकार',
    noBookmarks: 'अभी तक कोई बुकमार्क नहीं',
    readMore: 'और पढ़ें',
    revelation: 'रहस्योद्घाटन',
    ayahs: 'आयात',
    bismillah: 'शुरू अल्लाह के नाम से, जो बड़ा मेहरबान, निहायत रहम वाला है',
    prayerTimes: 'नमाज़ का समय',
    sahri: 'सहरी',
    iftar: 'इफ्तार',
    ramadanCountdown: 'रमज़ान उल-मुबारक',
    daysLeft: 'दिन बाकी',
    fajr: 'फज्र',
    dhuhr: 'ज़ुहर',
    asr: 'असर',
    maghrib: 'मग़रिब',
    isha: 'ईशा',
    currentLocation: 'स्थान खोज रहे हैं...',
    playRecitation: 'तिलावत सुनें',
    hadithCollection: 'हदीस संग्रह',
    audioQuran: 'ऑडियो क़ुरान',
    reciters: 'कारी',
    bookmarks: 'बुकमार्क',
    search: 'खोजें',
    tafsir: 'तफ़सीर',
    offlineContent: 'ऑफ़लाइन सामग्री',
    downloads: 'डाउनलोड',
    quranText: 'क़ुरान पाठ',
    audioFiles: 'ऑडियो फ़ाइलें',
    storageUsed: 'इस्तेमाल किया गया स्थान',
    manageDownloads: 'डाउनलोड प्रबंधित करें',
    downloading: 'डाउनलोड हो रहा है...',
    downloadComplete: 'डाउनलोड पूरा हुआ',
    deleteData: 'डेटा हटाएं',
    cacheCleared: 'कैश साफ किया गया',
    downloadAll: 'सभी डाउनलोड करें',
    aboutApp: 'ऐप के बारे में',
    developerInfo: 'डेवलपर जानकारी',
    donation: 'दान और समर्थन',
    developedBy: 'द्वारा विकसित',
    developerName: 'मो. शाहीन',
    developerRole: 'फुल स्टैक डेवलपर',
    donateMsg: 'यदि आपको यह ऐप पसंद है, तो कृपया इसे विज्ञापन-मुक्त और बनाए रखने के लिए हमारा समर्थन करें।',
    donateBtn: 'अभी दान करें',
    contact: 'संपर्क',
    email: 'ईमेल',
    donateTitle: 'अभी दान करें',
    bankAccount: 'बैंक खाता',
    personal: 'व्यक्तिगत',
    copied: 'कॉपी किया गया!',
    tasbih: 'तस्बीह',
    count: 'गिनती',
    reset: 'रीसेट',
    target: 'लक्ष्य',
    vibration: 'कंपन',
    games: 'इस्लामी सीखने के खेल',
    quizGame: 'क्विज़ मास्टर',
    timelineGame: 'इतिहास समयरेखा',
    surahGame: 'सूरा बिल्डर',
    score: 'स्कोर',
    playAgain: 'फिर से खेलें',
    correct: 'सही!',
    wrong: 'गलत!',
    nextQuestion: 'अगला प्रश्न',
    gameOver: 'खेल खत्म',
    finalScore: 'अंतिम स्कोर',
    start: 'शुरू',
    categories: 'श्रेणियाँ',
    prophets: 'पैगंबर',
    history: 'इतिहास',
    pillars: 'इस्लाम के स्तंभ',
    arrangeEvents: 'घटनाओं को क्रम में व्यवस्थित करें',
    arrangeAyahs: 'आयतों को क्रम में व्यवस्थित करें',
    checkOrder: 'क्रम की जाँच करें',
    tryAgain: 'पुनः प्रयास करें',
    correctOrder: 'सही क्रम!',
    wrongOrder: 'गलत क्रम',
    completed: 'पूरा हुआ'
  },
  ar: {
    home: 'الرئيسية',
    quran: 'القرآن',
    audio: 'صوت',
    hadis: 'حديث',
    settings: 'الإعدادات',
    lastRead: 'آخر قراءة',
    surahs: 'السور',
    juz: 'الأجزاء',
    language: 'اللغة',
    fontSize: 'حجم الخط',
    theme: 'المظهر',
    appearance: 'المظهر الخارجي',
    searchPlaceholder: 'ابحث عن سورة أو كلمة...',
    arabicFont: 'حجم الخط العربي',
    transFont: 'حجم خط الترجمة',
    noBookmarks: 'لا توجد محفوظات',
    readMore: 'اقرأ المزيد',
    revelation: 'مكان النزول',
    ayahs: 'الآيات',
    bismillah: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ',
    prayerTimes: 'مواقيت الصلاة',
    sahri: 'السحور',
    iftar: 'الإفطار',
    ramadanCountdown: 'العد التنازلي لرمضان',
    daysLeft: 'يوم متبقي',
    fajr: 'الفجر',
    dhuhr: 'الظهر',
    asr: 'العصر',
    maghrib: 'المغرب',
    isha: 'العشاء',
    currentLocation: 'تحديد الموقع...',
    playRecitation: 'استمع إلى التلاوة',
    hadithCollection: 'مجموعة الأحاديث',
    audioQuran: 'القرآن الصوتي',
    reciters: 'القراء',
    bookmarks: 'المحفوظات',
    search: 'بحث',
    tafsir: 'التفسير',
    offlineContent: 'المحتوى الصوتي',
    downloads: 'التنزيلات',
    quranText: 'نص القرآن',
    audioFiles: 'الملفات الصوتية',
    storageUsed: 'المساحة المستخدمة',
    manageDownloads: 'إدارة التنزيلات',
    downloading: 'جاري التحميل...',
    downloadComplete: 'اكتمل التحميل',
    deleteData: 'حذف البيانات',
    cacheCleared: 'تم مسح التخزين المؤقت',
    downloadAll: 'تحميل الكل',
    aboutApp: 'عن التطبيق',
    developerInfo: 'معلومات المطور',
    donation: 'الدعم والتبرع',
    developedBy: 'تطوير',
    developerName: 'محمد شاهين',
    developerRole: 'مطور مكدس كامل',
    donateMsg: 'إذا أعجبك هذا التطبيق، يرجى التفكير في دعمنا لإبقائه خاليًا من الإعلانات وصيانته.',
    donateBtn: 'تبرع الآن',
    contact: 'اتصال',
    email: 'البريد الإلكتروني',
    donateTitle: 'تبرع الآن',
    bankAccount: 'حساب بنكي',
    personal: 'شخصي',
    copied: 'تم النسخ!',
    tasbih: 'التسبيح',
    count: 'العدد',
    reset: 'إعادة تعيين',
    target: 'الهدف',
    vibration: 'الاهتزاز',
    games: 'ألعاب تعليمية إسلامية',
    quizGame: 'سيد المسابقة',
    timelineGame: 'الجدول الزمني للتاريخ',
    surahGame: 'بناء السورة',
    score: 'النتيجة',
    playAgain: 'العب مرة أخرى',
    correct: 'صحيح!',
    wrong: 'خطأ!',
    nextQuestion: 'السؤال التالي',
    gameOver: 'انتهت اللعبة',
    finalScore: 'النتيجة النهائية',
    start: 'ابدأ',
    categories: 'فئات',
    prophets: 'الأنبياء',
    history: 'التاريخ',
    pillars: 'أركان الإسلام',
    arrangeEvents: 'رتب الأحداث بالترتيب',
    arrangeAyahs: 'رتب الآيات بالترتيب',
    checkOrder: 'تحقق من الترتيب',
    tryAgain: 'حاول مرة أخرى',
    correctOrder: 'ترتيب صحيح!',
    wrongOrder: 'ترتيب خاطئ',
    completed: 'مكتمل'
  }
};

export const PRAYER_RAKATS = {
  Fajr: [
    { type: 'Sunnah', count: 2 },
    { type: 'Fard', count: 2 }
  ],
  Dhuhr: [
    { type: 'Sunnah', count: 4 },
    { type: 'Fard', count: 4 },
    { type: 'Sunnah', count: 2 },
    { type: 'Nafl', count: 2 }
  ],
  Asr: [
    { type: 'Sunnah', count: 4, note: 'Ghair Muakkadah' },
    { type: 'Fard', count: 4 }
  ],
  Maghrib: [
    { type: 'Fard', count: 3 },
    { type: 'Sunnah', count: 2 },
    { type: 'Nafl', count: 2 }
  ],
  Isha: [
    { type: 'Sunnah', count: 4, note: 'Ghair Muakkadah' },
    { type: 'Fard', count: 4 },
    { type: 'Sunnah', count: 2 },
    { type: 'Nafl', count: 2 },
    { type: 'Witr', count: 3 },
    { type: 'Nafl', count: 2 }
  ]
};

export const PRAYER_DUAS = {
  Fajr: {
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا، وَرِزْقًا طَيِّبًا، وَعَمَلاً مُتَقَبَّلاً",
    transliteration: "Allahumma inni as'aluka 'ilman nafi'an, wa rizqan tayyiban, wa 'amalan mutaqabbalan",
    translation: "O Allah, I ask You for beneficial knowledge, good provision, and acceptable deeds."
  },
  Dhuhr: {
    arabic: "اللَّهُمَّ اغْفِرْ لِي ذَنْبِي كُلَّهُ، دِقَّهُ وَجِلَّهُ، وَأَوَّلَهُ وَآخِرَهُ وَعَلَانِيَتَهُ وَسِرَّهُ",
    transliteration: "Allahumma-ghfir li dhanbi kullahu, diqqahu wa jillahu, wa awwalahu wa akhirahu wa 'alaniyatahu wa sirrahu",
    translation: "O Allah! Forgive all my sins, the small and great, the first and the last, the open and the secret."
  },
  Asr: {
    arabic: "أَسْتَغْفِرُ اللَّهَ الَّذِي لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ وَأَتُوبُ إِلَيْهِ",
    transliteration: "Astaghfirullah-alladhi la ilaha illa Huwal-Hayyul-Qayyum, wa atubu ilaih",
    translation: "I seek the forgiveness of Allah the Almighty, whom there is none worthy of worship except Him, The Living, The Eternal, and I turn to Him in repentance."
  },
  Maghrib: {
    arabic: "اللَّهُمَّ إِنَّ هَذَا إِقْبَالُ لَيْلِكَ، وَإِدْبَارُ نَهَارِكَ، وَأَصْوَاتُ دُعَاتِكَ، فَاغْفِرْ لِي",
    transliteration: "Allahumma inna hadha iqbalu laylika, wa idbaru naharika, wa aswatu du'atika, faghfir li",
    translation: "O Allah, this is the approach of Your night, the departure of Your day, and the voices of Your callers, so forgive me."
  },
  Isha: {
    arabic: "بِسْمِ اللَّهِ وَضَعْتُ جَنْبِي، اللَّهُمَّ اغْفِرْ لِي ذَنْبِي، وَاخْسَأْ شَيْطَانِي، وَفُكَّ رِهَانِي، وَاجْعَلْنِي فِي النَّدِيِّ الْأَعْلَى",
    transliteration: "Bismillahi wada'tu janbi, Allahumma-ghfir li dhanbi, wa akhsa' shaytani, wa fukka rihani, waj'alni fin-nadiyyil-a'la",
    translation: "In the name of Allah I lay down my side. O Allah, forgive my sin, drive away my devil, free me from my responsibility, and place me in the highest assembly."
  }
};

export const SURAH_LIST_STATIC = [
  { number: 1, name: "سُورَةُ الفَاتِحَةِ", englishName: "Al-Faatiha", englishNameTranslation: "The Opening", numberOfAyahs: 7, revelationType: "Meccan" },
  { number: 2, name: "سُورَةُ البَقَرَةِ", englishName: "Al-Baqara", englishNameTranslation: "The Cow", numberOfAyahs: 286, revelationType: "Medinan" },
];

export const APP_LANGUAGES = [
  { id: 'en', name: 'English', nativeName: 'English' },
  { id: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { id: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { id: 'ar', name: 'Arabic', nativeName: 'عربي' }
];
